apiVersion: v1
kind: Service

metadata:
  name: ollama-service
  labels:
    app: {{ include "ollama.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "ollama.fullname" . }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 11434
      protocol: TCP
