# ==========================================================
# PostgreSQL Image
# ==========================================================

image:
  repository: pgvector/pgvector
  tag: "pg15"
  pullPolicy: IfNotPresent


# ==========================================================
# PostgreSQL
# ==========================================================

postgres:
  user: postgres
  password: postgres

  databases:
    - project9_app
    - project9_rag


# ==========================================================
# Service
# ==========================================================

service:
  type: ClusterIP
  port: 5432


# ==========================================================
# Persistence
# ==========================================================

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""


# ==========================================================
# Initialization
# ==========================================================

initdb:
  enabled: true
