apiVersion: v1
kind: Secret
metadata:
  name: amazonmq-secret

type: Opaque

stringData:
  AMAZONMQ_USERNAME: {{ .Values.amazonmq.username | quote }}
  AMAZONMQ_PASSWORD: {{ .Values.amazonmq.password | quote }}
