#!/usr/bin/env python3
"""
generate_stress_test.py

TC-1102 — generates a YAML file with 100+ routes, all pointed at
one Lambda, to verify the module handles a large route count
without hitting for_each performance issues or AWS service quotas.

This intentionally writes to testing/, not apigatewayconfig/apis/
— copy it over manually when you're ready to run this specific
test, so it doesn't sit in the real API set by default.

Usage:
    python3 scripts/generate_stress_test.py [route_count]
"""

import sys
from pathlib import Path

ROUTE_COUNT = int(sys.argv[1]) if len(sys.argv) > 1 else 120

header = """# yaml-language-server: $schema=../../apigatewayconfig/schema/api-schema.json
###############################################################
# Phase 12 Test File — TC-1102 (100+ Routes)
#
# Generated by scripts/generate_stress_test.py -- do not hand-edit.
# Copy into apigatewayconfig/apis/ when ready to run this test.
###############################################################

enabled: true

api:
  name: stress-test-routes
  description: Phase 12 QA -- {count} routes on one Lambda
  protocol_type: HTTP

stage:
  name: dev
  auto_deploy: true

integrations:
  - name: stress-lambda
    type: LAMBDA
    config:
      function_arn: arn:aws:lambda:us-west-2:111111111111:function:stress-test-echo

routes:
""".format(count=ROUTE_COUNT)

methods = ["GET", "POST", "PUT", "DELETE"]
lines = [header]

for i in range(ROUTE_COUNT):
    method = methods[i % len(methods)]
    lines.append(f"  - path: /resource-{i}\n")
    lines.append(f"    method: {method}\n")
    lines.append("    integration: stress-lambda\n")

out_dir = Path("testing")
out_dir.mkdir(exist_ok=True)
out_path = out_dir / "tc1102-stress-test-routes.yaml"
out_path.write_text("".join(lines))

print(f"Wrote {ROUTE_COUNT} routes to {out_path}")
