from app.tools.terraform.init import execute as terraform_init
from app.tools.terraform.validate import execute as terraform_validate
from app.tools.terraform.plan import execute as terraform_plan
from app.tools.terraform.explain_plan import execute as terraform_explain_plan

from app.tools.terraform_state import execute as terraform_state
from app.tools.terraform_drift import execute as terraform_drift


# ============================================================
# TOOL EXECUTORS
# ============================================================

TOOL_EXECUTORS = {
    "terraform_init": terraform_init,
    "terraform_validate": terraform_validate,
    "terraform_plan": terraform_plan,
    "terraform_explain_plan": terraform_explain_plan,
    "terraform_state": terraform_state,
    "terraform_drift": terraform_drift,
}


# ============================================================
# OLLAMA TOOL DEFINITIONS
# ============================================================

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "terraform_init",
            "description": "Initialize the Terraform project in the configured working directory.",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "terraform_validate",
            "description": "Validate the Terraform configuration.",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "terraform_plan",
            "description": "Run terraform plan and show infrastructure changes.",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "terraform_explain_plan",
            "description": (
                "Explain the Terraform plan in a simple structured format. "
                "Separate newly created, modified, replaced, and destroyed resources."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "terraform_state",
            "description": (
                "Read the current Terraform state and return information "
                "about resources managed by Terraform."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "terraform_drift",
            "description": (
                "Detect Terraform infrastructure drift by comparing the "
                "Terraform configuration/state with the actual infrastructure."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
]


# ============================================================
# GET OLLAMA TOOLS
# ============================================================

def get_tools():
    """
    Return tool definitions in the format expected by Ollama.
    """

    return TOOLS


# ============================================================
# GET AVAILABLE TOOL NAMES
# ============================================================

def get_available_tools():
    """
    Return tool names for debugging, logging, or documentation.
    """

    return list(TOOL_EXECUTORS.keys())


# ============================================================
# EXECUTE TOOL
# ============================================================

def execute_tool(
    tool_name: str,
    arguments: dict | None = None,
    terraform_path: str | None = None,
):
    """
    Execute a registered Terraform tool.

    Parameters
    ----------
    tool_name:
        Name of the tool.

    arguments:
        Arguments generated by the LLM.

    terraform_path:
        Current Terraform working directory.
    """

    if arguments is None:
        arguments = {}

    executor = TOOL_EXECUTORS.get(tool_name)

    if executor is None:
        return {
            "status": "error",
            "message": f"Unknown Terraform tool: {tool_name}",
            "available_tools": get_available_tools(),
        }

    try:
        return executor(
            arguments=arguments,
            terraform_path=terraform_path,
        )

    except TypeError:
        # Backward compatibility for tools that only accept
        # terraform_path or have a different simple signature.
        try:
            return executor(terraform_path=terraform_path)

        except TypeError:
            try:
                return executor(terraform_path)

            except Exception as exc:
                return {
                    "status": "error",
                    "tool": tool_name,
                    "message": str(exc),
                }

    except Exception as exc:
        return {
            "status": "error",
            "tool": tool_name,
            "message": str(exc),
        }
