# ==========================================================
# Image
# ==========================================================

image:
  repository: mcp-chat-ui
  tag: "1.0.0"
  pullPolicy: IfNotPresent


# ==========================================================
# Application
# ==========================================================

app:
  port: 80


# ==========================================================
# AI Backend
# ==========================================================

backend:
  host: ai-mcp-client
  port: 8081


# ==========================================================
# Service
# ==========================================================

service:
  type: ClusterIP
  port: 80
