{
 "title": "SRE-AWS-EC2",
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/EC2",
     "metricName": "CPUUtilization",
     "statistic": "Average",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/EC2",
     "metricName": "NetworkIn",
     "statistic": "Average",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/EC2",
     "metricName": "NetworkOut",
     "statistic": "Average",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Status Check Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/EC2",
     "metricName": "StatusCheckFailed",
     "statistic": "Maximum",
     "queryMode": "Metrics"
    }
   ]
  }
 ]
}