
[FILTER]
    Name modify
    Match spring.*
    Add service spring-service
    Add environment dev

[OUTPUT]
    Name es
    Match spring.*
    Host elasticsearch
    Port 9200
    Logstash_Format On
    Logstash_Prefix spring-logs

[FILTER]
    Name modify
    Match python.*
    Add service python-service
    Add environment dev

[OUTPUT]
    Name es
    Match python.*
    Host elasticsearch
    Port 9200
    Logstash_Format On
    Logstash_Prefix python-logs

[FILTER]
    Name modify
    Match payment.*
    Add service payment-service
    Add environment prod

[OUTPUT]
    Name es
    Match payment.*
    Host elasticsearch
    Port 9200
    Logstash_Format On
    Logstash_Prefix payment-logs
