prometheus-node-exporter:
  enabled: false

alertmanager:
  enabled: true

grafana:
  enabled: true

prometheus:
  enabled: true

### ADD FOR SNOW ###

receivers:
  - name: servicenow
    webhook_configs:
      - url: http://servicenow-webhook.monitoring.svc.cluster.local:5000/alert

#alertmanager:
#  config:
#    global:
#      resolve_timeout: 5m

#    route:
#      receiver: servicenow

#    receivers:
#      - name: servicenow
#        webhook_configs:
#          - url: http://servicenow-webhook.monitoring.svc.cluster.local:5000/alert
