apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "spring-service.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "spring-service.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "spring-service.name" . }}

    spec:

      containers:

        - name: spring-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: spring-logs
              mountPath: /app/logs

          env:
            - name: DB_URL
              value: {{ .Values.env.DB_URL | quote }}

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret
                  key: DB_PASSWORD

            - name: PYTHON_SERVICE_URL
              value: {{ .Values.env.PYTHON_SERVICE_URL | quote }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: spring-logs
          hostPath:
            path: /var/log/apps/spring-service
            type: DirectoryOrCreate
