apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-service-config
data:

  # PostgreSQL
  DB_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  DB_USERNAME: {{ .Values.database.username | quote }}

  # Python
  PYTHON_SERVICE_URL: {{ .Values.python.serviceUrl | quote }}

  # Messaging
  MESSAGING_PROVIDER: {{ .Values.messaging.provider | quote }}
  MESSAGING_SOURCE: {{ .Values.messaging.source | quote }}
  MESSAGING_DESTINATION: {{ .Values.messaging.destination | quote }}

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.kafka.consumerGroupId | quote }}
  KAFKA_AUDIT_CONSUMER_GROUP_ID: {{ .Values.kafka.auditConsumerGroupId | quote }}

  # Amazon MQ
  AMAZONMQ_BROKER_URL: {{ .Values.amazonmq.brokerUrl | quote }}
  AMAZONMQ_QUEUE: {{ .Values.amazonmq.queue | quote }}

  # OpenTelemetry
  OTEL_SERVICE_NAME: {{ .Values.otel.serviceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
