apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: spring-service

  template:
    metadata:
      labels:
        app: spring-service

    spec:
      containers:

        - name: spring-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080

          envFrom:

            - configMapRef:
                name: spring-service-config

            - secretRef:
                name: spring-service-secret

          env:

            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName | quote }}

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
