apiVersion: v1
kind: Secret
metadata:
  name: spring-service-secret
type: Opaque
stringData:

  DB_PASSWORD: "postgres"

  AMAZONMQ_USERNAME: {{ .Values.amazonmq.username | quote }}
  AMAZONMQ_PASSWORD: {{ .Values.amazonmq.password | quote }}
